"""
Django settings for proyecto_permisos project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import environ
from pathlib import Path
import os
from django.urls import reverse_lazy

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [env.str("ALLOWED_HOSTS")]
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_permisos',
    'import_export'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_permisos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
            os.path.join(BASE_DIR, 'app_permisos/templates'),
            os.path.join(BASE_DIR, 'app_permisos/templates/modules'),
            os.path.join(BASE_DIR, 'app_permisos/templates/update_temp'),
            os.path.join(BASE_DIR, 'app_permisos/templates/visualizacion'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'autoescape': False,
        },
    },
]

# WSGI_APPLICATION = 'proyecto_permisos.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES={}

if env.str("TIPO_ENTORNO")=='desarrollo':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
if env.str("TIPO_ENTORNO") == "produccion":
    DATABASES = {
        'default': {
            'ENGINE':'mssql',
            'NAME': env.str("SQL_NAME_DATABASE2"),
            'USER': env.str("SQL_USER_DATABASE"),
            'PASSWORD':env.str("SQL_PASSWORD_DATABASE"),
            'HOST':env.str("SQL_HOST"),
            'PORT':'',
            'OPTIONS':{
                'driver': 'ODBC Driver 17 for SQL Server',
            }
        }
    } 

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

DATE_INPUT_FORMATS = ['%d/%m/%Y']

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "proyecto_permisos/static")]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Static
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AUTH_USER_MODEL = 'app_permisos.CustomUser'

#LOGIN
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('inicio')

#ENVIO DE CORREOS
# Configuración para enviar correos a través de Outlook
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Usar el backend SMTP
EMAIL_HOST = 'smtp.office365.com'  # Servidor SMTP de Outlook
EMAIL_PORT = 587  # Puerto SMTP para Outlook con TLS
# print(env.str("EMAIL_PRAC"))
# print(env.str("PASS_PRAC"))
EMAIL_HOST_USER = env.str("EMAIL_PRAC")
EMAIL_HOST_PASSWORD = env.str("PASS_PRAC")  # Contraseña de tu cuenta de Outlook
EMAIL_USE_TLS = True  # Usar TLS para la conexión segura con Outlook
EMAIL_USE_SSL = False  # No usar SSL (SSL es diferente de TLS)
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERTFILE = None


# Configuración adicional
DEFAULT_FROM_EMAIL =  env.str("EMAIL_PRAC")